package jua.vm;

public final class OPCodes {
    private OPCodes() {
        throw new AssertionError();
    }

    public static final int
            _nop = 0,
            _const_null = 1,
            _const_true = 2,
            _const_false = 3,
            _const_i_m1 = 4,
            _const_i_0 = 5,
            _const_i_1 = 6,
            _const_i_2 = 7,
            _dup = 8,
            _dup_x1 = 9,
            _dup_x2 = 10,
            _swap = 11,
            _dup2 = 12,
            _dup2_x1 = 13,
            _dup2_x2 = 14,
            _push = 15,
            _new_list = 16,
            _pop = 18,
            _pop2 = 19,
            _add = 20,
            _sub = 21,
            _mul = 22,
            _div = 23,
            _rem = 24,
            _bit_and = 25,
            _bit_or = 26,
            _bit_xor = 27,
            _bit_shl = 28,
            _bit_shr = 29,
            _len = 30,
            _pos = 31,
            _neg = 32,
            _bit_inv = 33,
            _load = 34,
            _load0 = 35,
            _load1 = 36,
            _load2 = 37,
            _store = 38,
            _store0 = 39,
            _store1 = 40,
            _store2 = 41,
            _inc = 42,
            _dec = 43,
            _a_load = 44,
            _a_store = 45,
            _a_dec = 46,
            _a_inc = 47,
            _goto = 48,
            _if_eq = 49,
            _if_ne = 50,
            _if_ge = 51,
            _if_lt = 52,
            _if_le = 53,
            _if_gt = 54,
            _if_bz = 55,
            _if_nbz = 56,
            _if_null = 57,
            _if_nnull = 58,
            _call = 63,
            _return = 64,
            _leave = 65;
}
